const PDFDocument = require("pdfkit");

const generateInterviewReport = (interview) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        margin: 50,
        size: "A4",
      });

      const buffers = [];

      doc.on("data", (chunk) => {
        buffers.push(chunk);
      });

      doc.on("end", () => {
        resolve(Buffer.concat(buffers));
      });

      // =========================
      // HEADER
      // =========================

      doc
        .fontSize(24)
        .text("AI INTERVIEW REPORT", {
          align: "center",
        });

      doc.moveDown(0.5);

      doc
        .fontSize(11)
        .text(
          "AI Interview Preparation Platform",
          {
            align: "center",
          }
        );

      doc.moveDown();

      doc
        .moveTo(50, doc.y)
        .lineTo(550, doc.y)
        .stroke();

      doc.moveDown();

      // =========================
      // PERFORMANCE SUMMARY
      // =========================

      doc
        .fontSize(18)
        .text("Performance Summary");

      doc.moveDown(0.5);

      doc.fontSize(12);

      doc.text(
        `Interview Score: ${
          interview.score || 0
        } / 100`
      );

      doc.text(
        `Category: ${
          interview.category || "Technical"
        }`
      );

      doc.text(
        `Difficulty: ${
          interview.difficulty || "Medium"
        }`
      );

      doc.text(
        `Interview Date: ${
          interview.createdAt
            ? new Date(
                interview.createdAt
              ).toLocaleString()
            : "N/A"
        }`
      );

      doc.moveDown();

      doc
        .moveTo(50, doc.y)
        .lineTo(550, doc.y)
        .stroke();

      doc.moveDown();

      // =========================
      // STRENGTHS
      // =========================

      doc
        .fontSize(18)
        .text("Strengths");

      doc.moveDown(0.5);

      const strengths =
        interview.feedback?.strengths || [];

      doc.fontSize(12);

      if (strengths.length > 0) {
        strengths.forEach((item) => {
          doc.text(`• ${item}`);
        });
      } else {
        doc.text(
          "No strengths available."
        );
      }

      doc.moveDown();

      // =========================
      // WEAKNESSES
      // =========================

      doc
        .fontSize(18)
        .text("Weaknesses");

      doc.moveDown(0.5);

      const weaknesses =
        interview.feedback?.weaknesses || [];

      doc.fontSize(12);

      if (weaknesses.length > 0) {
        weaknesses.forEach((item) => {
          doc.text(`• ${item}`);
        });
      } else {
        doc.text(
          "No weaknesses available."
        );
      }

      doc.moveDown();

      // =========================
      // SUGGESTIONS
      // =========================

      doc
        .fontSize(18)
        .text("Suggestions");

      doc.moveDown(0.5);

      const suggestions =
        interview.feedback?.suggestions || [];

      doc.fontSize(12);

      if (suggestions.length > 0) {
        suggestions.forEach((item) => {
          doc.text(`• ${item}`);
        });
      } else {
        doc.text(
          "No suggestions available."
        );
      }

      doc.moveDown();

      // =========================
      // OVERALL FEEDBACK
      // =========================

      doc
        .fontSize(18)
        .text("Overall Feedback");

      doc.moveDown(0.5);

      doc
        .fontSize(12)
        .text(
          interview.feedback
            ?.overallFeedback ||
            "No feedback available."
        );

      doc.moveDown(2);

      // =========================
      // FOOTER
      // =========================

      doc
        .moveTo(50, doc.y)
        .lineTo(550, doc.y)
        .stroke();

      doc.moveDown();

      doc
        .fontSize(10)
        .text(
          `Generated on ${new Date().toLocaleString()}`,
          {
            align: "center",
          }
        );

      doc.text(
        "Generated by AI Interview Preparation Platform",
        {
          align: "center",
        }
      );

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = generateInterviewReport;